def onepassword_secret_value(secret_url, account_url):
    local(['op', 'signin', '--account', account_url])
    return local(['op', 'read', secret_url], echo_off=True, quiet=True)

def onepassword_secret_values(secret_id, account_url):
    local(['op', 'signin', '--account', account_url])
    ret_vals = {}
    secret_json = local(['op', 'item', 'get', secret_id, '--format', 'json'], echo_off=True, quiet=True)
    secret_dict = decode_json(secret_json)
    for secret in secret_dict["fields"]:
        if secret_dict["category"] == 'PASSWORD' and secret['id'] in ['notesPlain', 'password']:
            continue
        ret_vals[secret['label']] = secret['value']
    return ret_vals